Sistema.MVC/Controllers/ConductoresController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Sistema.Modelos; // Asegúrate de que el modelo 'Conductor' esté disponible en esta ruta
using Gestion.API.Consumer;
using Sistema.Modelos.Modelos;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization; // Asegúrate de que la clase Crud<Conductor> esté correctamente configurada

namespace Sistema.MVC.Controllers
{
    [Authorize]
    public class ConductoresController : Controller
    {
        // GET: ConductoresController
        public ActionResult Index()
        {
            var data = Crud<Conductor>.GetAll();
            return View(data);
        }

        // GET: ConductoresController/Details/5
        public ActionResult Details(int id)
        {
            var data = Crud<Conductor>.GetById(id);
            return View(data);
        }

        // GET: ConductoresController/Create
        public ActionResult Create()
        {
            ViewBag.Camiones = GetCamiones();
            return View();
        }
        private List<SelectListItem> GetCamiones()
        {
            var paises = Crud<Camion>.GetAll();
            return paises.Select(p => new SelectListItem
            {
                Value = p.Codigo.ToString(),
                Text = p.Placa.ToString(),
            }).ToList();

        }

        // POST: ConductoresController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Conductor conductor)
        {
            try
            {
                Crud<Conductor>.Create(conductor);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        // GET: ConductoresController/Edit/5
        public ActionResult Edit(int id)
        {
            var data = Crud<Conductor>.GetById(id);
            ViewBag.Camiones = GetCamiones();
            return View(data);
        }

        // POST: ConductoresController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Conductor conductor)
        {
            try
            {
                Crud<Conductor>.Update(id, conductor);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        // GET: ConductoresController/Delete/5
        public ActionResult Delete(int id)
        {
            var conductor = Crud<Conductor>.GetById(id);
            return View(conductor);
        }

        // POST: ConductoresController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                Crud<Conductor>.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Error al eliminar el conductor. Asegúrese de que no esté asociado a otros registros.");
                return View();
            }
        }
    }
}

Sistema.MVC/Controllers/LicenciasController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Sistema.Modelos; // Asegúrate de que el modelo 'Licencia' esté disponible en esta ruta
using Gestion.API.Consumer;
using Sistema.Modelos.Modelos;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization; // Asegúrate de que la clase Crud<Licencia> esté correctamente configurada

namespace Sistema.MVC.Controllers
{
    [Authorize]
    public class LicenciasController : Controller
    {
        // GET: LicenciasController
        public ActionResult Index()
        {
            var data = Crud<Licencia>.GetAll();
            return View(data);
        }

        // GET: LicenciasController/Details/5
        public ActionResult Details(int id)
        {
            var licencia = Crud<Licencia>.GetById(id);
            return View(licencia);
        }

        // GET: LicenciasController/Create
        public ActionResult Create()
        {
            ViewBag.Conductores = GetConductores();
            return View();
        }
        private List<SelectListItem> GetConductores()
        {
            var paises = Crud<Conductor>.GetAll();
            return paises.Select(p => new SelectListItem
            {
                Value = p.Codigo.ToString(),
                Text = p.Nombre
            }).ToList();
        }

        // POST: LicenciasController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Licencia licencia)
        {
            try
            {
                Crud<Licencia>.Create(licencia);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        // GET: LicenciasController/Edit/5
        public ActionResult Edit(int id)
        {
            var licencia = Crud<Licencia>.GetById(id);
            ViewBag.Conductores = GetConductores();
            return View(licencia);
        }

        // POST: LicenciasController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Licencia licencia)
        {
            try
            {
                Crud<Licencia>.Update(id, licencia);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        // GET: LicenciasController/Delete/5
        public ActionResult Delete(int id)
        {
            var licencia = Crud<Licencia>.GetById(id);
            return View(licencia);
        }

        // POST: LicenciasController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                Crud<Licencia>.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Error al eliminar la licencia. Asegúrese de que no esté asociada a otros registros.");
                return View();
            }
        }
    }
}

Sistema.MVC/Views/Conductores/Create.cshtml
@model Sistema.Modelos.Modelos.Conductor
@using Sistema.Modelos.Modelos;
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Conductor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nacionalidad" class="control-label"></label>
                <input asp-for="Nacionalidad" class="form-control" />
                <span asp-validation-for="Nacionalidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edad" class="control-label"></label>
                <input asp-for="Edad" class="form-control" />
                <span asp-validation-for="Edad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <select asp-for="Genero" class="form-control">
                    <option value="">Seleccione un género</option>
                    @foreach (var item in Enum.GetValues(typeof(Genero)))
                    {
                        <option value="@item">@item</option>
                    }
                </select>
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="TipoSangre" class="control-label"></label>
                <select asp-for="TipoSangre" class="form-control">
                    <option value="">Seleccione un tipo de sangre</option>
                    @foreach (var item in Enum.GetValues(typeof(TipoSangre)))
                    {
                        <option value="@item">@item</option>
                    }
                </select>
                <span asp-validation-for="TipoSangre" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CamionCodigo" class="control-label">Camión</label>
                <select asp-for="CamionCodigo" class="form-control" asp-items="ViewBag.Camiones">
                    <option value="">Seleccione un camión</option>
                </select>
                <span asp-validation-for="CamionCodigo" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Sistema.MVC/Views/Conductores/Delete.cshtml
@model Sistema.Modelos.Modelos.Conductor

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Conductor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nacionalidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nacionalidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Edad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoSangre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoSangre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CamionCodigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CamionCodigo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Sistema.MVC/Views/Conductores/Details.cshtml
@model Sistema.Modelos.Modelos.Conductor

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Conductor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nacionalidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nacionalidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Edad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TipoSangre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TipoSangre)
        </dd>
        <dt class="col-sm-2">
            Camion Que Maneja
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Camion.Placa)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>
<table class="table">
    <thead>
        <tr>
            <th>Tipo Licencia</th>
            <th>Fecha Emisión</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var licencia in Model.Licencias)
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-controller="Licencias" asp-route-id="@licencia.Codigo">@licencia.TipoLicencia</a>
                </td>
                <td>
                    <a asp-action="Details" asp-controller="Licencias" asp-route-id="@licencia.Codigo">@licencia.FechaEmision</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Sistema.MVC/Views/Conductores/Edit.cshtml
@model Sistema.Modelos.Modelos.Conductor
@using Sistema.Modelos.Modelos;
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Conductor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Codigo" class="control-label"></label>
                <input asp-for="Codigo" class="form-control" readonly="readonly"/>
                <span asp-validation-for="Codigo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nacionalidad" class="control-label"></label>
                <input asp-for="Nacionalidad" class="form-control" />
                <span asp-validation-for="Nacionalidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edad" class="control-label"></label>
                <input asp-for="Edad" class="form-control" />
                <span asp-validation-for="Edad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <select asp-for="Genero" class="form-control">
                    <option value="">Seleccione un género</option>
                    @foreach (var item in Enum.GetValues(typeof(Genero)))
                    {
                        <option value="@item">@item</option>
                    }
                </select>
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="TipoSangre" class="control-label"></label>
                <select asp-for="TipoSangre" class="form-control">
                    <option value="">Seleccione un tipo de sangre</option>
                    @foreach (var item in Enum.GetValues(typeof(TipoSangre)))
                    {
                        <option value="@item">@item</option>
                    }
                </select>
                <span asp-validation-for="TipoSangre" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CamionCodigo" class="control-label">Camión</label>
                <select asp-for="CamionCodigo" class="form-control" asp-items="ViewBag.Camiones">
                    <option value="">Seleccione un camión</option>
                </select>
                <span asp-validation-for="CamionCodigo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Sistema.MVC/Views/Conductores/Index.cshtml
@model IEnumerable<Sistema.Modelos.Modelos.Conductor>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Codigo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nacionalidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Edad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genero)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoSangre)
            </th>
            <th>
                Camion/Placa
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Codigo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nacionalidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Edad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoSangre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Camion.Placa)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {  id=item.Codigo }) |
                @Html.ActionLink("Details", "Details", new { id=item.Codigo }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.Codigo })
            </td>
        </tr>
}
    </tbody>
</table>