Sistema.MVC/Controllers/CamionesController.cs
using Gestion.API.Consumer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Sistema.Modelos;
using Sistema.Modelos.Modelos;

namespace Sistema.MVC.Controllers
{
    [Authorize]
    public class CamionesController : Controller
    {
        // GET: CamionesController
        public ActionResult Index()
        {
            var data = Crud<Camion>.GetAll();

            return View(data);
        }

        // GET: CamionesController/Details/5
        public ActionResult Details(int id)
        {
            var data = Crud<Camion>.GetById(id);
            return View(data);
        }

        // GET: CamionesController/Create
        public ActionResult Create()
        { 
            return View();
        }
        
        // POST: CamionesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Camion camion)
        {
            try
            {
                Crud<Camion>.Create(camion);
                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        // GET: CamionesController/Edit/5
        public ActionResult Edit(int id)
        {
            var camion = Crud<Camion>.GetById(id);
            return View(camion);
        }

        // POST: CamionesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Camion camion)
        {
            try
            {
                Crud<Camion>.Update(id,camion);
                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        // GET: CamionesController/Delete/5
        public ActionResult Delete(int id)
        {
            var camion = Crud<Camion>.GetById(id);
            return View(camion);
        }

        // POST: CamionesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                Crud<Camion>.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Error al eliminar el camión. Asegúrese de que no esté asociado a otros registros.");
                return View();
            }
        }
    }
}

Sistema.MVC/Controllers/ConductoresController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Sistema.Modelos; // Asegúrate de que el modelo 'Conductor' esté disponible en esta ruta
using Gestion.API.Consumer;
using Sistema.Modelos.Modelos;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization; // Asegúrate de que la clase Crud<Conductor> esté correctamente configurada

namespace Sistema.MVC.Controllers
{
    [Authorize]
    public class ConductoresController : Controller
    {
        // GET: ConductoresController
        public ActionResult Index()
        {
            var data = Crud<Conductor>.GetAll();
            return View(data);
        }

        // GET: ConductoresController/Details/5
        public ActionResult Details(int id)
        {
            var data = Crud<Conductor>.GetById(id);
            return View(data);
        }

        // GET: ConductoresController/Create
        public ActionResult Create()
        {
            ViewBag.Camiones = GetCamiones();
            return View();
        }
        private List<SelectListItem> GetCamiones()
        {
            var paises = Crud<Camion>.GetAll();
            return paises.Select(p => new SelectListItem
            {
                Value = p.Codigo.ToString(),
                Text = p.Placa.ToString(),
            }).ToList();

        }

        // POST: ConductoresController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Conductor conductor)
        {
            try
            {
                Crud<Conductor>.Create(conductor);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        // GET: ConductoresController/Edit/5
        public ActionResult Edit(int id)
        {
            var data = Crud<Conductor>.GetById(id);
            ViewBag.Camiones = GetCamiones();
            return View(data);
        }

        // POST: ConductoresController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Conductor conductor)
        {
            try
            {
                Crud<Conductor>.Update(id, conductor);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        // GET: ConductoresController/Delete/5
        public ActionResult Delete(int id)
        {
            var conductor = Crud<Conductor>.GetById(id);
            return View(conductor);
        }

        // POST: ConductoresController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                Crud<Conductor>.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Error al eliminar el conductor. Asegúrese de que no esté asociado a otros registros.");
                return View();
            }
        }
    }
}

Sistema.MVC/Views/Camiones/Create.cshtml
@model Sistema.Modelos.Camion
@using Sistema.Modelos;
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Camion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Anio" class="control-label"></label>
                <input asp-for="Anio" class="form-control" />
                <span asp-validation-for="Anio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Placa" class="control-label"></label>
                <input asp-for="Placa" class="form-control" />
                <span asp-validation-for="Placa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KilometrajeActual" class="control-label"></label>
                <input asp-for="KilometrajeActual" class="form-control" />
                <span asp-validation-for="KilometrajeActual" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <select asp-for="Estado" class="form-control">
                    <option value="">Seleccione un estado</option>
                    @foreach (var item in Enum.GetValues(typeof(Estado)))
                    {
                        <option value="@item">@item</option>
                    }
                </select>
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Sistema.MVC/Views/Camiones/Delete.cshtml
@model Sistema.Modelos.Camion

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Camion</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Anio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Anio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Placa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Placa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KilometrajeActual)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KilometrajeActual)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Sistema.MVC/Views/Camiones/Details.cshtml
@model Sistema.Modelos.Camion

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Camion</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Anio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Anio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Placa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Placa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.KilometrajeActual)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.KilometrajeActual)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>
<table class="table">
    <thead>
        <tr>
            <th>Conductor</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var conductor in Model.Conductores)
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-controller="Conductores" asp-route-id="@conductor.Codigo">@conductor.Nombre</a>
                </td>
            </tr>
        }  
    </tbody>
</table>
<table class="table">
    <thead>
        <tr>
            <th>Mantenimiento/Descripcion</th>
            <th>Fecha Programada</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var mantenimiento in Model.MantenimientosProgramados)
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-controller="Conductores" asp-route-id="@mantenimiento.Codigo">@mantenimiento.Descripcion</a>
                </td>
                <td>
                    <a asp-action="Details" asp-controller="Conductores" asp-route-id="@mantenimiento.Codigo">@mantenimiento.FechaProgramada</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Sistema.MVC/Views/Camiones/Edit.cshtml
@model Sistema.Modelos.Camion
@using Sistema.Modelos;
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Camion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Codigo" class="control-label"></label>
                <input asp-for="Codigo" class="form-control" readonly="readonly"/>
                <span asp-validation-for="Codigo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Anio" class="control-label"></label>
                <input asp-for="Anio" class="form-control" />
                <span asp-validation-for="Anio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Placa" class="control-label"></label>
                <input asp-for="Placa" class="form-control" readonly = "readonly"/>
                <span asp-validation-for="Placa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KilometrajeActual" class="control-label"></label>
                <input asp-for="KilometrajeActual" class="form-control" />
                <span asp-validation-for="KilometrajeActual" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <select asp-for="Estado" class="form-control">
                    <option value="">Seleccione un estado</option>
                    @foreach (var item in Enum.GetValues(typeof(Estado)))
                    {
                        <option value="@item">@item</option>
                    }
                </select>
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Sistema.MVC/Views/Camiones/Index.cshtml
@model IEnumerable<Sistema.Modelos.Camion>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Codigo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modelo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Anio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Placa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KilometrajeActual)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Codigo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Modelo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Anio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Placa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KilometrajeActual)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Codigo}) |
                    @Html.ActionLink("Details", "Details", new { id = item.Codigo }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Codigo })
            </td>
        </tr>
}
    </tbody>
</table>