Sistema.MVC/Controllers/MantenimientosProgramadosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Sistema.Modelos; // Asegúrate de que el modelo 'MantenimientoProgramado' esté disponible en esta ruta
using Gestion.API.Consumer;
using Sistema.Modelos.Modelos;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization; // Asegúrate de que la clase Crud<MantenimientoProgramado> esté correctamente configurada

namespace Sistema.MVC.Controllers
{
    [Authorize]
    public class MantenimientosProgramadosController : Controller
    {
        // GET: MantenimientosProgramadosController
        public ActionResult Index()
        {
            var data = Crud<MantenimientoProgramado>.GetAll();
            ViewBag.TotalRegistros = data.Count;
            return View(data);
        }

        // GET: MantenimientosProgramadosController/Details/5
        public ActionResult Details(int id)
        {
            var mantenimiento = Crud<MantenimientoProgramado>.GetById(id);

            return View(mantenimiento);
        }

        // GET: MantenimientosProgramadosController/Create
        public ActionResult Create()
        {
            ViewBag.Camiones = GetCamiones();
            ViewBag.Talleres = GetTalleres();
            return View();
        }
        private List<SelectListItem> GetCamiones()
        {
            var paises = Crud<Camion>.GetAll();
            return paises.Select(p => new SelectListItem
            {
                Value = p.Codigo.ToString(),
                Text = p.Placa.ToString(),
            }).ToList();
        }
        private List<SelectListItem> GetTalleres()
        {
            var paises = Crud<Taller>.GetAll();
            return paises.Select(p => new SelectListItem
            {
                Value = p.Codigo.ToString(),
                Text = p.Nombre,
            }).ToList();
        }
        // POST: MantenimientosProgramadosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MantenimientoProgramado mantenimiento)
        {
            try
            {
                Crud<MantenimientoProgramado>.Create(mantenimiento);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        // GET: MantenimientosProgramadosController/Edit/5
        public ActionResult Edit(int id)
        {
            var mantenimiento = Crud<MantenimientoProgramado>.GetById(id);
            ViewBag.Camiones = GetCamiones();
            ViewBag.Talleres = GetTalleres();

            return View(mantenimiento);
        }

        // POST: MantenimientosProgramadosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, MantenimientoProgramado mantenimiento)
        {
            try
            {
                Crud<MantenimientoProgramado>.Update(id, mantenimiento);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        // GET: MantenimientosProgramadosController/Delete/5
        public ActionResult Delete(int id)
        {
            var mantenimiento = Crud<MantenimientoProgramado>.GetById(id);
            return View(mantenimiento);
        }

        // POST: MantenimientosProgramadosController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                Crud<MantenimientoProgramado>.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Error al eliminar el mantenimiento programado. Asegúrese de que no esté asociado a otros registros.");
                return View();
            }
        }

        [HttpPost("realizar-mantenimiento")]
        [ValidateAntiForgeryToken]
        public ActionResult RealizarMantenimiento(int id)
        {
            try
            {
                // Obtén el mantenimiento programado por su id
                var mantenimiento = Crud<MantenimientoProgramado>.GetById(id);

                // Actualiza la fecha y el estado
                mantenimiento.FechaRealizada = DateTime.Now;
                mantenimiento.Estado = MantenimientoProgramado.EstadoMantenimiento.Finalizado;

                // Obtén el camión y actualiza el kilometraje
                var camion = Crud<Camion>.GetById(mantenimiento.CamionCodigo);
                mantenimiento.Kilometraje = camion.KilometrajeActual;

                // Guarda los cambios en la base de datos
                Crud<MantenimientoProgramado>.Update(id, mantenimiento);

                // Redirige a la vista "Index" después de completar el mantenimiento
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                // Si hay un error, muestra el mensaje de error
                ModelState.AddModelError("", ex.Message);
                return RedirectToAction("Index");
            }
        }


    }
}

Sistema.MVC/Views/MantenimientosProgramados/Create.cshtml
@model Sistema.Modelos.Modelos.MantenimientoProgramado
@using Sistema.Modelos;
@using Sistema.Modelos.Modelos;

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>MantenimientoProgramado</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="FechaProgramada" class="control-label"></label>
                <input asp-for="FechaProgramada" class="form-control" />
                <span asp-validation-for="FechaProgramada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaRealizada" class="control-label"></label>
                <input asp-for="FechaRealizada" class="form-control" />
                <span asp-validation-for="FechaRealizada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                <select asp-for="Tipo" class="form-control">
                    <option value="">Seleccione un tipo</option>
                    @foreach (var item in Enum.GetValues(typeof(MantenimientoProgramado.TipoMantenimiento)))
                    {
                        <option value="@item">@item</option>
                    }
                </select>
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <select asp-for="Estado" class="form-control">
                    <option value="">Seleccione un estado de mantenimiento</option>
                    @foreach (var item in Enum.GetValues(typeof(MantenimientoProgramado.EstadoMantenimiento)))
                    {
                        <option value="@item">@item</option>
                    }
                </select>
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CamionCodigo" class="control-label">Camión</label>
                <select asp-for="CamionCodigo" class="form-control" asp-items="ViewBag.Camiones">
                    <option value="">Seleccione un camión</option>
                </select>
                <span asp-validation-for="CamionCodigo" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Kilometraje" class="control-label"></label>
                <input asp-for="Kilometraje" class="form-control" />
                <span asp-validation-for="Kilometraje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TallerCodigo" class="control-label">Taller</label>
                <select asp-for="TallerCodigo" class="form-control" asp-items="ViewBag.Talleres">
                    <option value="">Seleccione un taller</option>
                </select>
                <span asp-validation-for="TallerCodigo" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Sistema.MVC/Views/MantenimientosProgramados/Delete.cshtml
@model Sistema.Modelos.Modelos.MantenimientoProgramado

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MantenimientoProgramado</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaProgramada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaProgramada)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaRealizada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaRealizada)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tipo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Kilometraje)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Kilometraje)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CamionCodigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CamionCodigo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TallerCodigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TallerCodigo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>

    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Sistema.MVC/Views/MantenimientosProgramados/Details.cshtml
@model Sistema.Modelos.Modelos.MantenimientoProgramado

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>MantenimientoProgramado</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Codigo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaProgramada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaProgramada)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaRealizada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaRealizada)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tipo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Kilometraje)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Kilometraje)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CamionCodigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CamionCodigo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TallerCodigo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TallerCodigo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Sistema.MVC/Views/MantenimientosProgramados/Edit.cshtml
@model Sistema.Modelos.Modelos.MantenimientoProgramado
@using Sistema.Modelos;
@using Sistema.Modelos.Modelos;
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>MantenimientoProgramado</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Codigo" class="control-label"></label>
                <input asp-for="Codigo" class="form-control" readonly ="readonly"/>
                <span asp-validation-for="Codigo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaProgramada" class="control-label"></label>
                <input asp-for="FechaProgramada" class="form-control" />
                <span asp-validation-for="FechaProgramada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaRealizada" class="control-label"></label>
                <input asp-for="FechaRealizada" class="form-control" />
                <span asp-validation-for="FechaRealizada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                <select asp-for="Tipo" class="form-control">
                    <option value="">Seleccione un tipo</option>
                    @foreach (var item in Enum.GetValues(typeof(MantenimientoProgramado.TipoMantenimiento)))
                    {
                        <option value="@item">@item</option>
                    }
                </select>
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Kilometraje" class="control-label"></label>
                <input asp-for="Kilometraje" class="form-control" />
                <span asp-validation-for="Kilometraje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CamionCodigo" class="control-label">Camión</label>
                <select asp-for="CamionCodigo" class="form-control" asp-items="ViewBag.Camiones">
                    <option value="">Seleccione un camión</option>
                </select>
                <span asp-validation-for="CamionCodigo" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="TallerCodigo" class="control-label">Taller</label>
                <select asp-for="TallerCodigo" class="form-control" asp-items="ViewBag.Talleres">
                    <option value="">Seleccione un taller</option>
                </select>
                <span asp-validation-for="TallerCodigo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <select asp-for="Estado" class="form-control">
                    <option value="">Seleccione un estado de mantenimiento</option>
                    @foreach (var item in Enum.GetValues(typeof(MantenimientoProgramado.EstadoMantenimiento)))
                    {
                        <option value="@item">@item</option>
                    }
                </select>
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Sistema.MVC/Views/MantenimientosProgramados/Index.cshtml
@model IEnumerable<Sistema.Modelos.Modelos.MantenimientoProgramado>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Codigo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaProgramada)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaRealizada)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tipo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Kilometraje)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CamionCodigo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TallerCodigo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Codigo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaProgramada)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaRealizada)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tipo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Kilometraje)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CamionCodigo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TallerCodigo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {  id=item.Codigo }) |
                @Html.ActionLink("Details", "Details", new { id=item.Codigo }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.Codigo })
                @using (Html.BeginForm("RealizarMantenimiento", "MantenimientosProgramados", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.Hidden("id", item.Codigo) <!-- Aseguramos que el id se pase como un campo oculto -->
                    <button type="submit" class="btn btn-success">Realizar Mantenimiento</button>
                }

            </td>
        </tr>
}
    </tbody>
</table>